config/routes.rb
Friendcircle::Application.routes.draw do

  get "static/home"
  
  root :to => 'static#home'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :users
  resources :friendships, :only => [:index, :show, :new, :create, :destroy]

  match '/sign_up', :to => "users#new"
  match '/log_in', :to => "sessions#new"
  match '/log_out', :to => "sessions#destroy", via: :delete

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :friend_id

  belongs_to :user
  belongs_to :friend, class_name: "User"

  validates :user_id, :presence => true
  validates :friend_id, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username

  validates :username, :presence => true, :uniqueness => true

  #Specify the friendship from This Model -> Other User
  has_many :friendships, :dependent => :destroy
  has_many :friends, :through => :friendships
  
  #Specify the inverse friendship from Other User -> This User
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => :friend_id, :dependent => :destroy
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  # callback functions for saving user
  before_validation { |user| user.username = user.username.downcase.strip }

  before_save :generate_token


  # check if there's a friendship in both users' friends
  def friend_of?(user)
    !friends.where(:id => user.id)[0].nil? && !inverse_friends.where(:id => user.id)[0].nil?
  end

  # check if there's a friendship request from the user
  def friend_request_received?(user)
    friends.where(:id => user.id)[0].nil? && !inverse_friends.where(:id => user.id)[0].nil?
  end

  # check if the user is awaiting a response to the friend request
  def friend_request_sent?(user)
    !friends.where(:id => user.id)[0].nil? && inverse_friends.where(:id => user.id)[0].nil?
  end

  # get friends list
  def friend_list
     friend_arr = []
     friends.each do |f|
       if(self.friend_of?(f))
         friend_arr.push(f)
       end
     end

     friend_arr
  end

  # get friend requests list 
  def friend_request_list
    friend_request_arr = []

    inverse_friends.each do |f|
      if self.friend_request_received?(f)
        friend_request_arr.push(f)
      end
    end

    friend_request_arr
  end


  # get awaiting requests list 
  def awaiting_friend_request_list
    friend_request_arr = []

    friends.each do |f|
      if f.friend_request_received?(self)
        friend_request_arr.push(f)
      end
    end

    friend_request_arr
  end

  private

    def generate_token
      self.session_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper

  private

    def correct_user
      @user = User.where(id: params[:id])[0]
      redirect_to(root_path) unless current_user?(@user)
    end

    def logged_in
      redirect_to new_session_path unless !current_user.nil?
    end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  before_filter :logged_in, :only => [ :destroy, :create, :index, :show ]

  def new
    @user = User.new
  end

  def index
    @user = current_user
  end

  def show
    @user = User.where(:id => params[:id])[0]
  end

  def create

    if params[:id].nil?
      @friend = User.where(:username => params[:user][:username])[0] 
    else
      @friend = User.where(:id => params[:id])[0]
    end

    if !@friend.nil? && @friend != current_user
      @friendship = current_user.friendships.build(:friend_id => @friend.id)

      if @friendship.save
        flash[:success] = "Added Friend"
      else
        flash[:error] = "Unable to add friend"
      end
    else
      flash[:error] = "Couldn't add user as friend, user must exist and not be current user"
    end
    redirect_to user_path(current_user)
  end

  def destroy
    @friendship = current_user.friendships.where(:friend_id => params[:id])[0]
    @inverse_friendship = current_user.inverse_friendships.where(:user_id => params[:id])[0]

    if @friendship.nil? && @inverse_friendship.nil?
      flash[:error] = "There was an issue removing friendship"
    else
      @friendship.destroy unless @friendship.nil?
      @inverse_friendship.destroy unless @inverse_friendship.nil?

      flash[:success] = "Friendship was removed successfully"
    end

    redirect_to user_path(current_user)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.where(:username => params[:session][:username].downcase)[0]

    if user.nil?
      flash[:error] = "Couldn't login that user. click new user to create a new account"
      render 'new'
    else
      sign_in user
      redirect_to user
    end
      
  end

  def destroy
    if signed_in?
      sign_out
      flash[:success] = "Successfully logged out"
    else
      flash[:error] = "Unable to process request"    
    end

    redirect_to root_path

  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :correct_user, :only => [:destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      flash[:success] = "Welcome to FriendCircle"
      sign_in @user
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.where(id: params[:id])[0]

    if @user.nil?
      @user = User.new
      render 'new'
    end
  end

  def destroy
    @user = User.where(id: params[:id])[0]

    if @user
      if @user.destroy
        flash[:success] = "User account was successfully removed"
      else
        flash[:error] = "There was a problem unregistering the user"
      end
    else
      flash[:error] = "There was a problem finding the user to unregister"
    end
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:session_token] = user.session_token
    self.current_user = user
  end

  def current_user
    @current_user ||= User.where(:session_token => cookies[:session_token])[0] 
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user?(user)
    current_user == user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    self.current_user = nil;
    cookies.delete(:session_token)
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/_friends.html.erb
<h3><%= @user.username.capitalize %> Friends</h3>
<ul>
<% if @user.friend_list.count == 0 %>
  <p>No friends yet. <%= link_to "Add friends", new_friendship_path %></p>
<% else %>
  <% @user.friend_list.each do |f| %>
    <li><%= f.username %> <%= link_to "profile", user_path(f) %> <%= link_to "View Friends", friendship_path(f) %> <%= link_to "remove", friendship_path(f.id), :method => :DELETE %></li>
  <% end %>
<% end %>
</ul>

app/views/friendships/index.html.erb
<h1>Friendships for <%= @user.username %></h1>

<h3>Received Friend Requests</h3>
<ul>
<% @user.friend_request_list.each do |f| %>
  <li><%= f.username %> <%= link_to "accept", friendships_path(f,:id => f.id), :method => :POST %>
    <%= link_to "decline", friendship_path(f.id), :method => :DELETE %></li>
<% end %>
</ul>

<h3>Sent Friend Requests</h3>
<ul>
<% @user.awaiting_friend_request_list.each do |f| %>
  <li><%= f.username %> <%= link_to "remove", friendship_path(f.id), :method => :DELETE %></li>
<% end %>
</ul>

<%= render 'friendships/friends' %>

app/views/friendships/new.html.erb
<h1>Add Friends</h1>

<%= form_for(@user, :url => friendships_path) do |u| %>
  <%= u.label :username %>
  <%= u.text_field :username %>

  <%= u.submit "Add Friend", :class => "btn btn-primary" %>
<% end %>

app/views/friendships/show.html.erb
<% if @user == current_user || current_user.friend_of?(@user) %>
  <%= render 'friendships/friends' %>
<% else %>
  Must be friends with <%= @user.username %> to see their friends
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "FriendCircle", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">

        <% if signed_in? %>
          <li><p class="navbar-text">signed in as <%= current_user.username %></p></li> 
          <li><%= link_to "Profile", user_path(current_user) %></li>
          <li><%= link_to "Log Out", log_out_path, :method => :DELETE%></li>
        <% else %>
          <li><%= link_to "Sign Up", sign_up_path %></li> 
          <li><%= link_to "Login", log_in_path %></li>
        <% end %>

        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Friendcircle</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  
  <div class="container">

    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
<div class="errors">
  <div class="alert alert-error">
    There was a problem with your form
  </div>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render 'error_messages' %>
<div class="span4 row">
<%= form_for(@user) do |u| %>
  <p><%= u.label :username %></p>
  <%= u.text_field :username %>

  <p class="pull-right"><%= u.submit "sign up", :class => "btn btn-primary" %></p>
<% end %>
</div>

app/views/users/show.html.erb
<h1>User Profile</h1>

<p>Username: <%= @user.username %></p>
<p>Friends: <b>(<%= @user.friend_list.count %>)</b></p>

<% if current_user?(@user) %>
  <%= link_to "View Friends", friendship_path(@user), :class => 'btn' %>
  <%= link_to "Add Friends", new_friendship_path, :class => 'btn'  %>
  <%= link_to "Remove Friends", friendships_path, :class => 'btn'  %>
  <%= link_to "Friend Requests", friendships_path, :class => 'btn'  %>
  <%= link_to "Unregister", user_path, :method => :DELETE, :class => 'btn', data: { confirm: "Are you sure? All information will be permanently deleted" }  %>
<% else %>
  <% if !current_user.nil? %>
    <% if @user.friend_of?(current_user) %>
      <%= link_to "Remove Friend", friendship_path(@user.id), :class => 'btn', :method => :DELETE,  data: { confirm: "Are you sure you want to remove friend?" } %>
      <%= link_to "View Friends", friendship_path(@user), :class => 'btn' %>
    <% else %>
      <% if current_user.friend_request_sent?(@user) %>
        Awaiting Response
      <% else %>
        <%= link_to "Add Friend", friendships_path(@user,:id => @user.id), :class => 'btn', :method => :POST, data: { confirm: "Are you sure you want to add friend?" } %>
      <% end %>
    <% end %>
  <% end %>
<% end %>